# Generated by Django 3.1.3 on 2020-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pasword',
            field=models.CharField(default='root', max_length=255),
        ),
    ]
