# Generated by Django 3.1.3 on 2020-11-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201124_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='writableUser',
            field=models.BooleanField(default=True),
        ),
    ]
