# Generated by Django 3.1.3 on 2020-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201125_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='readable',
            new_name='readableGuest',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='writable',
            new_name='readableRoot',
        ),
        migrations.AddField(
            model_name='file',
            name='readableUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='writableGuest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='writableRoot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='writableUser',
            field=models.BooleanField(default=True),
        ),
    ]
